# slackチャンネル及びarxiv学問領域の指定
channels:
        astro-ph_ga:
                subject: 'cat:astro-ph.GA'
                keywords:
                        hoge: 1
        astro-ph_co: 
                subject: 'cat:astro-ph.CO'
                keywords:
                        hoge: 1
        astro-ph_ep: 
                subject: 'cat:astro-ph.EP'
                keywords:
                        huga: 1
        astro-ph_he: 
                subject: 'cat:astro-ph.HE'
                keywords:
                        huga: 1
        astro-ph_im: 
                subject: 'cat:astro-ph.IM'
                keywords:
                        hoge: 1
        astro-ph_sr: 
                subject: 'cat:astro-ph.SR'
                keywords:
                        huga: 1
        

# 通知の閾値
score_threshold: 0
