# slackチャンネル及びarxiv学問領域の指定
channels:
        ASTROPH_GA:
                subject: 'cat:astro-ph.GA'
                keywords:
                        galaxy: 1
        ASTROPH_CO: 
                subject: 'cat:astro-ph.CO'
                keywords:
                        cosmology: 1
        ASTROPH_EP: 
                subject: 'cat:astro-ph.EP'
                keywords:
                        planet: 1
        ASTROPH_HE: 
                subject: 'cat:astro-ph.HE'
                keywords:
                        high energy: 1
        ASTROPH_IM: 
                subject: 'cat:astro-ph.IM'
                keywords:
                        instrumentation: 1
        ASTROPH_SR: 
                subject: 'cat:astro-ph.SR'
                keywords:
                        solar: 1
        
        
# 通知の閾値
score_threshold: 0
