# slackチャンネル及びarxiv学問領域の指定
channels:
        ASTROPH_GA:
                subject: 'cat:astro-ph.GA'
                keywords:
                        hoge: 1
        ASTROPH_CO: 
                subject: 'cat:astro-ph.CO'
                keywords:
                        hoge: 1
        ASTROPH_EP: 
                subject: 'cat:astro-ph.EP'
                keywords:
                        huga: 1
        ASTROPH_HE: 
                subject: 'cat:astro-ph.HE'
                keywords:
                        huga: 1
        ASTROPH_IM: 
                subject: 'cat:astro-ph.IM'
                keywords:
                        hoge: 1
        ASTROPH_SR: 
                subject: 'cat:astro-ph.SR'
                keywords:
                        huga: 1
        
        
# 通知の閾値
score_threshold: 0
