# arxivの学問領域の指定
subject: 'cat:astro-ph.GA'

# 検索キーワード
keywords:
        galaxy: 1
        high-z: 1
        cluster: 3
        protocluster: 3
        void: 3
        overdensity: 3
        underdensity: 3
# 通知の閾値
score_threshold: 1
