name: Carrier Owl

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron:  '00 4 * * 1,2,3,4,5'
  workflow_dispatch:
  
  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - 
        name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt update
          sudo apt-get install google-chrome-beta

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2

      - name: install dependencies
        run: poetry install
        
#       - name: Install Chrome
#         uses: browser-actions/setup-chrome@latest
#         with:
#             chrome-version: 972766
#       - name: Check Chrome version
#         run: chrome --version
        
      - name: Run owl
        run:
          poetry run python src/carrier_owl.py
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_ID: ${{ secrets.SLACK_BOT_ID }}
          SLACK_CHANNEL_ID_DEV: ${{ secrets.SLACK_CHANNEL_ID_DEV }}
          MENTION_URL: ${{secrets.MENTION_URL}}
#           SLACK_ID_ASTROPH_GA: ${{ secrets.SLACK_ID_ASTROPH_GA }}
#           SLACK_ID_ASTROPH_CO: ${{ secrets.SLACK_ID_ASTROPH_CO }}
#           SLACK_ID_ASTROPH_HE: ${{ secrets.SLACK_ID_ASTROPH_HE }}
#           SLACK_ID_ASTROPH_EP: ${{ secrets.SLACK_ID_ASTROPH_EP }}
#           SLACK_ID_ASTROPH_IM: ${{ secrets.SLACK_ID_ASTROPH_IM }}
#           SLACK_ID_ASTROPH_SR: ${{ secrets.SLACK_ID_ASTROPH_SR }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}


